### ISSUE TITLE
Inconsistent bbox annotations in COCO format annotation file and gt.txt

### ISSUE THREAD

**Issue by wangyirui** [dvl-tum/motsynth-baselines#10]
Hi, I found that some bounding box annotations are labeled as area=0 but still appear in the gt.txt file. 

For example, in the 0089 video, frame 21:

> {
>             "id": 890020000466,
>             "image_id": 890020,
>             "category_id": 1,
>             "segmentation":
>             {
>                 "size":
>                 [
>                     1080,
>                     1920
>                 ],
>                 "counts": "PPYo1"
>             },
>             **"area": 0.0,**
>             "bbox":
>             [
>                 854,
>                 562,
>                 **4,**
>                 **27**
>             ]
> }

I am wondering do you have a threshold to determine if the area should be set as 0.0? Shall we modify this area value or remove this object from the gt.txt?

Thank you!

**Comment by guillembraso** [comment]
Hi, 

Sorry for my late reply. `area` refers to the segmentation mask area of the given object, you can compute it yourself from the provided RLE mask using `pycocotools`.

We still include boxes with `area= 0`(i.e. totally invisible) within trajectories in both the `.json` COCO format annotation files and MOT format `gt.txt` files. This is done for consistency with other MOTChallenge datasets (MOT15, MOT16, MOT17, and MOT20). Note that boxes with `area=0` will have their visibility set to 0 (9th column in MOT format files)!

The reasoning is that even though a box might be invisible for a few frames due to occlusion, a good multi-object tracker should be able to recover its rough location by applying linear interpolation or a motion model to the visible segments of the trajectory.

Best,

Guillem

**Comment by wangyirui** [comment]
> Hi,
> 
> Sorry for my late reply. `area` refers to the segmentation mask area of the given object, you can compute it yourself from the provided RLE mask using `pycocotools`.
> 
> We still include boxes with `area= 0`(i.e. totally invisible) within trajectories in both the `.json` COCO format annotation files and MOT format `gt.txt` files. This is done for consistency with other MOTChallenge datasets (MOT15, MOT16, MOT17, and MOT20). Note that boxes with `area=0` will have their visibility set to 0 (9th column in MOT format files)!
> 
> The reasoning is that even though a box might be invisible for a few frames due to occlusion, a good multi-object tracker should be able to recover its rough location by applying linear interpolation or a motion model to the visible segments of the trajectory.
> 
> Best,
> 
> Guillem

Understood. Thanks for your clarification!
